const PLAYERS_DATA = [
    {
        id: "curry",
        name: "Stephen Curry",
        number: 30,
        team: "Golden State Warriors",
        teamAbbr: "GSW",
        position: "PG",
        height: 188,
        weight: 84,
        age: 36,
        experience: 15,
        draft: { year: 2009, round: 1, pick: 7 },
        salary: "$55,761,216",
        ratings: {
            scoring: 96,
            efficiency: 95,
            ballHandling: 94,
            offBall: 98,
            clutch: 97,
            defense: 72,
            perimeter: 75,
            interior: 45,
            rebounding: 55,
            steals: 78,
            blocks: 40,
            playmaking: 94,
            turnover: 85,
            leadership: 92,
            durability: 82,
            athleticism: 80,
            stamina: 90,
            basketballIQ: 98,
            decisionMaking: 96,
            impact: 95
        },
        advanced: {
            per: 24.7,
            ws: 12.3,
            bpm: 8.5,
            vorp: 4.2,
            trueShooting: 62.6,
            usage: 30.2
        },
        honors: ["4× NBA Champion", "2× MVP", "9× All-Star", "1× Finals MVP", "9× All-NBA Team"]
    },
    {
        id: "jokic",
        name: "Nikola Jokic",
        number: 15,
        team: "Denver Nuggets",
        teamAbbr: "DEN",
        position: "C",
        height: 208,
        weight: 113,
        age: 29,
        experience: 9,
        draft: { year: 2014, round: 2, pick: 41 },
        salary: "$51,415,938",
        ratings: {
            scoring: 94,
            efficiency: 98,
            ballHandling: 90,
            offBall: 88,
            clutch: 92,
            defense: 78,
            perimeter: 60,
            interior: 88,
            rebounding: 95,
            steals: 70,
            blocks: 75,
            playmaking: 98,
            turnover: 78,
            leadership: 90,
            durability: 88,
            athleticism: 72,
            stamina: 92,
            basketballIQ: 99,
            decisionMaking: 98,
            impact: 97
        },
        advanced: {
            per: 31.3,
            ws: 15.2,
            bpm: 12.4,
            vorp: 5.8,
            trueShooting: 65.2,
            usage: 29.8
        },
        honors: ["3× NBA Champion", "3× MVP", "6× All-Star", "1× Finals MVP", "6× All-NBA Team"]
    },
    {
        id: "giannis",
        name: "Giannis Antetokounmpo",
        number: 34,
        team: "Milwaukee Bucks",
        teamAbbr: "MIL",
        position: "PF",
        height: 211,
        weight: 110,
        age: 29,
        experience: 11,
        draft: { year: 2013, round: 1, pick: 15 },
        salary: "$48,787,207",
        ratings: {
            scoring: 96,
            efficiency: 88,
            ballHandling: 85,
            offBall: 70,
            clutch: 88,
            defense: 94,
            perimeter: 82,
            interior: 98,
            rebounding: 93,
            steals: 78,
            blocks: 88,
            playmaking: 85,
            turnover: 72,
            leadership: 88,
            durability: 82,
            athleticism: 99,
            stamina: 92,
            basketballIQ: 88,
            decisionMaking: 85,
            impact: 94
        },
        advanced: {
            per: 27.1,
            ws: 14.8,
            bpm: 9.8,
            vorp: 5.1,
            trueShooting: 58.4,
            usage: 32.5
        },
        honors: ["2× NBA Champion", "2× MVP", "1× Finals MVP", "8× All-Star", "8× All-NBA Team", "4× All-Defensive Team"]
    },
    {
        id: "doncic",
        name: "Luka Doncic",
        number: 77,
        team: "Los Angeles Lakers",
        teamAbbr: "LAL",
        position: "PG",
        height: 201,
        weight: 104,
        age: 25,
        experience: 6,
        draft: { year: 2018, round: 1, pick: 3 },
        salary: "$43,031,750",
        ratings: {
            scoring: 97,
            efficiency: 85,
            ballHandling: 96,
            offBall: 72,
            clutch: 95,
            defense: 68,
            perimeter: 70,
            interior: 72,
            rebounding: 82,
            steals: 68,
            blocks: 55,
            playmaking: 96,
            turnover: 70,
            leadership: 88,
            durability: 78,
            athleticism: 75,
            stamina: 88,
            basketballIQ: 96,
            decisionMaking: 94,
            impact: 93
        },
        advanced: {
            per: 28.4,
            ws: 10.2,
            bpm: 9.2,
            vorp: 4.5,
            trueShooting: 58.1,
            usage: 35.8
        },
        honors: ["5× All-Star", "5× All-NBA Team", "Rookie of the Year"]
    },
    {
        id: "embiid",
        name: "Joel Embiid",
        number: 21,
        team: "Los Angeles Clippers",
        teamAbbr: "LAC",
        position: "C",
        height: 213,
        weight: 127,
        age: 30,
        experience: 8,
        draft: { year: 2014, round: 1, pick: 3 },
        salary: "$55,541,779",
        ratings: {
            scoring: 97,
            efficiency: 89,
            ballHandling: 85,
            offBall: 72,
            clutch: 92,
            defense: 88,
            perimeter: 65,
            interior: 95,
            rebounding: 92,
            steals: 72,
            blocks: 92,
            playmaking: 78,
            turnover: 68,
            leadership: 82,
            durability: 72,
            athleticism: 85,
            stamina: 85,
            basketballIQ: 90,
            decisionMaking: 84,
            impact: 91
        },
        advanced: {
            per: 29.8,
            ws: 11.8,
            bpm: 8.9,
            vorp: 4.0,
            trueShooting: 59.2,
            usage: 33.5
        },
        honors: ["1× MVP", "7× All-Star", "5× All-NBA Team", "2× All-Defensive Team", "Scoring Champion"]
    },
    {
        id: "durant",
        name: "Kevin Durant",
        number: 35,
        team: "Phoenix Suns",
        teamAbbr: "PHX",
        position: "SF",
        height: 208,
        weight: 109,
        age: 35,
        experience: 17,
        draft: { year: 2007, round: 1, pick: 2 },
        salary: "$54,272,727",
        ratings: {
            scoring: 98,
            efficiency: 92,
            ballHandling: 90,
            offBall: 92,
            clutch: 95,
            defense: 78,
            perimeter: 80,
            interior: 72,
            rebounding: 72,
            steals: 68,
            blocks: 65,
            playmaking: 82,
            turnover: 80,
            leadership: 85,
            durability: 75,
            athleticism: 85,
            stamina: 82,
            basketballIQ: 94,
            decisionMaking: 90,
            impact: 92
        },
        advanced: {
            per: 26.2,
            ws: 14.5,
            bpm: 6.8,
            vorp: 3.8,
            trueShooting: 61.5,
            usage: 29.5
        },
        honors: ["2× NBA Champion", "2× Finals MVP", "1× MVP", "14× All-Star", "11× All-NBA Team", "Rookie of the Year"]
    },
    {
        id: "lebron",
        name: "LeBron James",
        number: 23,
        team: "Los Angeles Lakers",
        teamAbbr: "LAL",
        position: "SF",
        height: 206,
        weight: 113,
        age: 39,
        experience: 21,
        draft: { year: 2003, round: 1, pick: 1 },
        salary: "$48,721,020",
        ratings: {
            scoring: 94,
            efficiency: 90,
            ballHandling: 92,
            offBall: 85,
            clutch: 93,
            defense: 84,
            perimeter: 82,
            interior: 88,
            rebounding: 88,
            steals: 75,
            blocks: 65,
            playmaking: 95,
            turnover: 78,
            leadership: 99,
            durability: 78,
            athleticism: 85,
            stamina: 95,
            basketballIQ: 99,
            decisionMaking: 96,
            impact: 98
        },
        advanced: {
            per: 23.5,
            ws: 18.2,
            bpm: 7.5,
            vorp: 4.2,
            trueShooting: 60.8,
            usage: 29.2
        },
        honors: ["4× NBA Champion", "4× Finals MVP", "4× MVP", "20× All-Star", "20× All-NBA Team", "Rookie of the Year"]
    },
    {
        id: "antetokounmpo",
        name: "Luka Doncic",
        number: 77,
        team: "Dallas Mavericks",
        teamAbbr: "DAL",
        position: "PG",
        height: 201,
        weight: 104,
        age: 25,
        experience: 6,
        draft: { year: 2018, round: 1, pick: 3 },
        salary: "$43,031,750",
        ratings: {
            scoring: 95,
            efficiency: 84,
            ballHandling: 95,
            offBall: 70,
            clutch: 93,
            defense: 70,
            perimeter: 72,
            interior: 75,
            rebounding: 80,
            steals: 70,
            blocks: 52,
            playmaking: 95,
            turnover: 72,
            leadership: 86,
            durability: 80,
            athleticism: 78,
            stamina: 86,
            basketballIQ: 95,
            decisionMaking: 92,
            impact: 92
        },
        advanced: {
            per: 27.8,
            ws: 9.8,
            bpm: 8.8,
            vorp: 4.2,
            trueShooting: 57.5,
            usage: 36.2
        },
        honors: ["5× All-Star", "5× All-NBA Team"]
    },
    {
        id: "tatum",
        name: "Jayson Tatum",
        number: 0,
        team: "Boston Celtics",
        teamAbbr: "BOS",
        position: "SF",
        height: 203,
        weight: 95,
        age: 26,
        experience: 7,
        draft: { year: 2017, round: 1, pick: 3 },
        salary: "$36,016,200",
        ratings: {
            scoring: 92,
            efficiency: 86,
            ballHandling: 88,
            offBall: 85,
            clutch: 88,
            defense: 84,
            perimeter: 85,
            interior: 78,
            rebounding: 78,
            steals: 72,
            blocks: 58,
            playmaking: 80,
            turnover: 82,
            leadership: 82,
            durability: 90,
            athleticism: 86,
            stamina: 88,
            basketballIQ: 88,
            decisionMaking: 84,
            impact: 86
        },
        advanced: {
            per: 23.8,
            ws: 11.5,
            bpm: 5.2,
            vorp: 3.2,
            trueShooting: 58.8,
            usage: 29.8
        },
        honors: ["1× NBA Champion", "4× All-Star", "2× All-NBA Team"]
    },
    {
        id: "butler",
        name: "Jimmy Butler",
        number: 22,
        team: "Miami Heat",
        teamAbbr: "MIA",
        position: "SF",
        height: 203,
        weight: 95,
        age: 34,
        experience: 13,
        draft: { year: 2011, round: 1, pick: 30 },
        salary: "$48,787,207",
        ratings: {
            scoring: 88,
            efficiency: 88,
            ballHandling: 86,
            offBall: 75,
            clutch: 94,
            defense: 90,
            perimeter: 88,
            interior: 85,
            rebounding: 72,
            steals: 82,
            blocks: 55,
            playmaking: 82,
            turnover: 85,
            leadership: 92,
            durability: 75,
            athleticism: 82,
            stamina: 90,
            basketballIQ: 92,
            decisionMaking: 94,
            impact: 90
        },
        advanced: {
            per: 22.5,
            ws: 10.8,
            bpm: 4.8,
            vorp: 2.8,
            trueShooting: 61.2,
            usage: 26.5
        },
        honors: ["2× NBA Champion", "6× All-Star", "5× All-NBA Team", "4× All-Defensive Team"]
    },
    {
        id: "davis",
        name: "Anthony Davis",
        number: 3,
        team: "Los Angeles Lakers",
        teamAbbr: "LAL",
        position: "PF",
        height: 208,
        weight: 106,
        age: 31,
        experience: 12,
        draft: { year: 2012, round: 1, pick: 1 },
        salary: "$43,219,333",
        ratings: {
            scoring: 90,
            efficiency: 88,
            ballHandling: 78,
            offBall: 80,
            clutch: 86,
            defense: 95,
            perimeter: 78,
            interior: 95,
            rebounding: 95,
            steals: 78,
            blocks: 96,
            playmaking: 72,
            turnover: 80,
            leadership: 80,
            durability: 75,
            athleticism: 90,
            stamina: 85,
            basketballIQ: 90,
            decisionMaking: 82,
            impact: 90
        },
        advanced: {
            per: 25.8,
            ws: 12.5,
            bpm: 6.5,
            vorp: 3.5,
            trueShooting: 59.5,
            usage: 27.8
        },
        honors: ["1× NBA Champion", "9× All-Star", "4× All-NBA Team", "3× All-Defensive Team"]
    },
    {
        id: "booker",
        name: "Devin Booker",
        number: 1,
        team: "Phoenix Suns",
        teamAbbr: "PHX",
        position: "SG",
        height: 196,
        weight: 93,
        age: 27,
        experience: 9,
        draft: { year: 2015, round: 1, pick: 13 },
        salary: "$36,016,200",
        ratings: {
            scoring: 94,
            efficiency: 88,
            ballHandling: 88,
            offBall: 92,
            clutch: 90,
            defense: 72,
            perimeter: 72,
            interior: 65,
            rebounding: 58,
            steals: 65,
            blocks: 45,
            playmaking: 80,
            turnover: 80,
            leadership: 82,
            durability: 88,
            athleticism: 84,
            stamina: 90,
            basketballIQ: 86,
            decisionMaking: 82,
            impact: 84
        },
        advanced: {
            per: 24.2,
            ws: 9.5,
            bpm: 4.2,
            vorp: 2.5,
            trueShooting: 60.5,
            usage: 31.2
        },
        honors: ["1× NBA Champion", "4× All-Star", "2× All-NBA Team"]
    },
    {
        id: "edwards",
        name: "Anthony Edwards",
        number: 5,
        team: "Minnesota Timberwolves",
        teamAbbr: "MIN",
        position: "SG",
        height: 196,
        weight: 102,
        age: 23,
        experience: 4,
        draft: { year: 2020, round: 1, pick: 1 },
        salary: "$42,332,400",
        ratings: {
            scoring: 91,
            efficiency: 84,
            ballHandling: 88,
            offBall: 82,
            clutch: 85,
            defense: 78,
            perimeter: 80,
            interior: 78,
            rebounding: 65,
            steals: 72,
            blocks: 50,
            playmaking: 75,
            turnover: 78,
            leadership: 78,
            durability: 92,
            athleticism: 95,
            stamina: 90,
            basketballIQ: 82,
            decisionMaking: 78,
            impact: 82
        },
        advanced: {
            per: 22.5,
            ws: 8.8,
            bpm: 3.8,
            vorp: 2.2,
            trueShooting: 56.8,
            usage: 28.5
        },
        honors: ["1× All-Star", "1× All-NBA Team", "Rookie of the Year"]
    },
    {
        id: "george",
        name: "Paul George",
        number: 8,
        team: "Philadelphia 76ers",
        teamAbbr: "PHI",
        position: "SG",
        height: 203,
        weight: 100,
        age: 34,
        experience: 14,
        draft: { year: 2010, round: 1, pick: 10 },
        salary: "$49,212,860",
        ratings: {
            scoring: 88,
            efficiency: 85,
            ballHandling: 86,
            offBall: 88,
            clutch: 86,
            defense: 86,
            perimeter: 88,
            interior: 72,
            rebounding: 65,
            steals: 80,
            blocks: 55,
            playmaking: 78,
            turnover: 82,
            leadership: 80,
            durability: 75,
            athleticism: 86,
            stamina: 84,
            basketballIQ: 88,
            decisionMaking: 86,
            impact: 84
        },
        advanced: {
            per: 21.5,
            ws: 11.2,
            bpm: 4.5,
            vorp: 2.8,
            trueShooting: 58.5,
            usage: 27.2
        },
        honors: ["1× NBA Champion", "8× All-Star", "6× All-NBA Team", "4× All-Defensive Team"]
    },
    {
        id: "brown",
        name: "Jaylen Brown",
        number: 7,
        team: "Boston Celtics",
        teamAbbr: "BOS",
        position: "SG",
        height: 198,
        weight: 101,
        age: 27,
        experience: 8,
        draft: { year: 2016, round: 1, pick: 3 },
        salary: "$49,212,860",
        ratings: {
            scoring: 89,
            efficiency: 85,
            ballHandling: 86,
            offBall: 82,
            clutch: 86,
            defense: 84,
            perimeter: 86,
            interior: 80,
            rebounding: 68,
            steals: 75,
            blocks: 52,
            playmaking: 76,
            turnover: 80,
            leadership: 80,
            durability: 88,
            athleticism: 92,
            stamina: 88,
            basketballIQ: 84,
            decisionMaking: 82,
            impact: 84
        },
        advanced: {
            per: 22.8,
            ws: 10.2,
            bpm: 4.8,
            vorp: 2.8,
            trueShooting: 59.2,
            usage: 28.8
        },
        honors: ["1× NBA Champion", "3× All-Star", "1× All-NBA Team"]
    },
    {
        id: "williams",
        name: "Jalen Williams",
        number: 8,
        team: "Oklahoma City Thunder",
        teamAbbr: "OKC",
        position: "SG",
        height: 196,
        weight: 88,
        age: 23,
        experience: 2,
        draft: { year: 2022, round: 1, pick: 12 },
        salary: "$5,414,784",
        ratings: {
            scoring: 82,
            efficiency: 88,
            ballHandling: 84,
            offBall: 80,
            clutch: 78,
            defense: 82,
            perimeter: 82,
            interior: 72,
            rebounding: 58,
            steals: 75,
            blocks: 50,
            playmaking: 78,
            turnover: 84,
            leadership: 72,
            durability: 92,
            athleticism: 86,
            stamina: 88,
            basketballIQ: 84,
            decisionMaking: 82,
            impact: 78
        },
        advanced: {
            per: 21.5,
            ws: 6.8,
            bpm: 4.2,
            vorp: 1.8,
            trueShooting: 62.8,
            usage: 24.5
        },
        honors: ["1× All-Star"]
    },
    {
        id: "gilgeous",
        name: "Shai Gilgeous-Alexander",
        number: 2,
        team: "Oklahoma City Thunder",
        teamAbbr: "OKC",
        position: "PG",
        height: 198,
        weight: 88,
        age: 25,
        experience: 6,
        draft: { year: 2018, round: 1, pick: 11 },
        salary: "$35,000,000",
        ratings: {
            scoring: 94,
            efficiency: 90,
            ballHandling: 94,
            offBall: 78,
            clutch: 90,
            defense: 84,
            perimeter: 85,
            interior: 78,
            rebounding: 68,
            steals: 82,
            blocks: 62,
            playmaking: 90,
            turnover: 80,
            leadership: 84,
            durability: 90,
            athleticism: 90,
            stamina: 90,
            basketballIQ: 90,
            decisionMaking: 90,
            impact: 90
        },
        advanced: {
            per: 29.2,
            ws: 12.5,
            bpm: 10.2,
            vorp: 5.2,
            trueShooting: 62.5,
            usage: 31.8
        },
        honors: ["2× All-Star", "2× All-NBA Team"]
    },
    {
        id: "holiday",
        name: "Jrue Holiday",
        number: 4,
        team: "Boston Celtics",
        teamAbbr: "BOS",
        position: "PG",
        height: 193,
        weight: 93,
        age: 33,
        experience: 15,
        draft: { year: 2009, round: 1, pick: 17 },
        salary: "$32,000,000",
        ratings: {
            scoring: 80,
            efficiency: 88,
            ballHandling: 86,
            offBall: 80,
            clutch: 84,
            defense: 92,
            perimeter: 92,
            interior: 72,
            rebounding: 58,
            steals: 88,
            blocks: 55,
            playmaking: 86,
            turnover: 85,
            leadership: 82,
            durability: 85,
            athleticism: 82,
            stamina: 88,
            basketballIQ: 90,
            decisionMaking: 88,
            impact: 86
        },
        advanced: {
            per: 20.5,
            ws: 10.8,
            bpm: 5.2,
            vorp: 2.8,
            trueShooting: 61.5,
            usage: 22.5
        },
        honors: ["2× NBA Champion", "2× All-Star", "2× All-Defensive Team"]
    },
    {
        id: "wembanyama",
        name: "Victor Wembanyama",
        number: 1,
        team: "San Antonio Spurs",
        teamAbbr: "SAS",
        position: "C",
        height: 224,
        weight: 109,
        age: 20,
        experience: 1,
        draft: { year: 2023, round: 1, pick: 1 },
        salary: "$12,178,200",
        ratings: {
            scoring: 85,
            efficiency: 78,
            ballHandling: 80,
            offBall: 72,
            clutch: 75,
            defense: 92,
            perimeter: 85,
            interior: 88,
            rebounding: 88,
            steals: 72,
            blocks: 98,
            playmaking: 75,
            turnover: 72,
            leadership: 70,
            durability: 70,
            athleticism: 92,
            stamina: 85,
            basketballIQ: 82,
            decisionMaking: 76,
            impact: 80
        },
        advanced: {
            per: 21.5,
            ws: 4.8,
            bpm: 3.8,
            vorp: 1.5,
            trueShooting: 54.2,
            usage: 28.8
        },
        honors: ["Rookie of the Year", "1× All-Star"]
    },
    {
        id: "towns",
        name: "Karl-Anthony Towns",
        number: 32,
        team: "New York Knicks",
        teamAbbr: "NYK",
        position: "C",
        height: 213,
        weight: 112,
        age: 28,
        experience: 9,
        draft: { year: 2015, round: 1, pick: 1 },
        salary: "$49,212,860",
        ratings: {
            scoring: 88,
            efficiency: 90,
            ballHandling: 80,
            offBall: 82,
            clutch: 80,
            defense: 78,
            perimeter: 68,
            interior: 88,
            rebounding: 92,
            steals: 62,
            blocks: 80,
            playmaking: 75,
            turnover: 78,
            leadership: 78,
            durability: 80,
            athleticism: 78,
            stamina: 84,
            basketballIQ: 86,
            decisionMaking: 82,
            impact: 82
        },
        advanced: {
            per: 24.2,
            ws: 10.5,
            bpm: 4.8,
            vorp: 2.8,
            trueShooting: 63.5,
            usage: 26.8
        },
        honors: ["1× NBA Champion", "3× All-Star", "2× All-NBA Team"]
    },
    {
        id: "brunson",
        name: "Jalen Brunson",
        number: 11,
        team: "New York Knicks",
        teamAbbr: "NYK",
        position: "PG",
        height: 185,
        weight: 86,
        age: 27,
        experience: 7,
        draft: { year: 2018, round: 1, pick: 33 },
        salary: "$26,463,732",
        ratings: {
            scoring: 88,
            efficiency: 90,
            ballHandling: 90,
            offBall: 72,
            clutch: 90,
            defense: 72,
            perimeter: 72,
            interior: 65,
            rebounding: 52,
            steals: 68,
            blocks: 42,
            playmaking: 88,
            turnover: 78,
            leadership: 86,
            durability: 92,
            athleticism: 75,
            stamina: 92,
            basketballIQ: 90,
            decisionMaking: 90,
            impact: 86
        },
        advanced: {
            per: 24.5,
            ws: 9.8,
            bpm: 5.2,
            vorp: 2.8,
            trueShooting: 62.8,
            usage: 29.5
        },
        honors: ["1× All-Star", "1× All-NBA Team"]
    },
    {
        id: "leonard",
        name: "Kawhi Leonard",
        number: 2,
        team: "Los Angeles Clippers",
        teamAbbr: "LAC",
        position: "SF",
        height: 201,
        weight: 102,
        age: 32,
        experience: 13,
        draft: { year: 2011, round: 1, pick: 15 },
        salary: "$48,787,207",
        ratings: {
            scoring: 88,
            efficiency: 90,
            ballHandling: 84,
            offBall: 80,
            clutch: 90,
            defense: 92,
            perimeter: 92,
            interior: 85,
            rebounding: 75,
            steals: 85,
            blocks: 62,
            playmaking: 76,
            turnover: 86,
            leadership: 82,
            durability: 65,
            athleticism: 90,
            stamina: 80,
            basketballIQ: 92,
            decisionMaking: 90,
            impact: 88
        },
        advanced: {
            per: 24.5,
            ws: 11.8,
            bpm: 6.8,
            vorp: 3.2,
            trueShooting: 62.8,
            usage: 28.5
        },
        honors: ["2× NBA Champion", "2× Finals MVP", "5× All-Star", "3× All-NBA Team", "2× All-Defensive Team"]
    },
    {
        id: "mitchell",
        name: "Donovan Mitchell",
        number: 45,
        team: "Cleveland Cavaliers",
        teamAbbr: "CLE",
        position: "SG",
        height: 191,
        weight: 98,
        age: 27,
        experience: 7,
        draft: { year: 2017, round: 1, pick: 13 },
        salary: "$35,000,000",
        ratings: {
            scoring: 90,
            efficiency: 84,
            ballHandling: 88,
            offBall: 82,
            clutch: 88,
            defense: 78,
            perimeter: 80,
            interior: 75,
            rebounding: 62,
            steals: 75,
            blocks: 48,
            playmaking: 80,
            turnover: 78,
            leadership: 82,
            durability: 86,
            athleticism: 92,
            stamina: 90,
            basketballIQ: 84,
            decisionMaking: 82,
            impact: 84
        },
        advanced: {
            per: 23.5,
            ws: 9.5,
            bpm: 4.5,
            vorp: 2.5,
            trueShooting: 58.2,
            usage: 30.5
        },
        honors: ["4× All-Star", "1× All-NBA Team"]
    },
    {
        id: "defo",
        name: "De'Aaron Fox",
        number: 5,
        team: "Sacramento Kings",
        teamAbbr: "SAC",
        position: "PG",
        height: 193,
        weight: 84,
        age: 26,
        experience: 7,
        draft: { year: 2017, round: 1, pick: 5 },
        salary: "$35,000,000",
        ratings: {
            scoring: 90,
            efficiency: 86,
            ballHandling: 92,
            offBall: 72,
            clutch: 88,
            defense: 72,
            perimeter: 72,
            interior: 70,
            rebounding: 58,
            steals: 80,
            blocks: 45,
            playmaking: 84,
            turnover: 78,
            leadership: 80,
            durability: 88,
            athleticism: 95,
            stamina: 90,
            basketballIQ: 84,
            decisionMaking: 84,
            impact: 84
        },
        advanced: {
            per: 25.8,
            ws: 8.8,
            bpm: 5.2,
            vorp: 2.5,
            trueShooting: 60.5,
            usage: 32.8
        },
        honors: ["1× All-Star"]
    },
    {
        id: "banchero",
        name: "Paolo Banchero",
        number: 5,
        team: "Orlando Magic",
        teamAbbr: "ORL",
        position: "PF",
        height: 208,
        weight: 113,
        age: 21,
        experience: 2,
        draft: { year: 2022, round: 1, pick: 1 },
        salary: "$11,655,480",
        ratings: {
            scoring: 84,
            efficiency: 80,
            ballHandling: 84,
            offBall: 68,
            clutch: 78,
            defense: 75,
            perimeter: 72,
            interior: 82,
            rebounding: 78,
            steals: 62,
            blocks: 58,
            playmaking: 78,
            turnover: 74,
            leadership: 75,
            durability: 88,
            athleticism: 88,
            stamina: 86,
            basketballIQ: 82,
            decisionMaking: 78,
            impact: 78
        },
        advanced: {
            per: 20.8,
            ws: 5.2,
            bpm: 2.8,
            vorp: 1.2,
            trueShooting: 54.5,
            usage: 28.8
        },
        honors: ["Rookie of the Year"]
    },
    {
        id: "zion",
        name: "Zion Williamson",
        number: 1,
        team: "New Orleans Pelicans",
        teamAbbr: "NOP",
        position: "PF",
        height: 198,
        weight: 128,
        age: 23,
        experience: 5,
        draft: { year: 2019, round: 1, pick: 1 },
        salary: "$36,016,200",
        ratings: {
            scoring: 90,
            efficiency: 82,
            ballHandling: 85,
            offBall: 70,
            clutch: 80,
            defense: 68,
            perimeter: 60,
            interior: 88,
            rebounding: 82,
            steals: 65,
            blocks: 62,
            playmaking: 72,
            turnover: 70,
            leadership: 75,
            durability: 60,
            athleticism: 98,
            stamina: 78,
            basketballIQ: 78,
            decisionMaking: 75,
            impact: 80
        },
        advanced: {
            per: 26.5,
            ws: 6.5,
            bpm: 4.2,
            vorp: 1.5,
            trueShooting: 61.5,
            usage: 30.5
        },
        honors: ["2× All-Star"]
    },
    {
        id: "morant",
        name: "Ja Morant",
        number: 12,
        team: "Memphis Grizzlies",
        teamAbbr: "MEM",
        position: "PG",
        height: 191,
        weight: 79,
        age: 25,
        experience: 5,
        draft: { year: 2019, round: 1, pick: 2 },
        salary: "$36,016,200",
        ratings: {
            scoring: 90,
            efficiency: 82,
            ballHandling: 94,
            offBall: 68,
            clutch: 85,
            defense: 72,
            perimeter: 72,
            interior: 70,
            rebounding: 55,
            steals: 72,
            blocks: 45,
            playmaking: 88,
            turnover: 72,
            leadership: 82,
            durability: 68,
            athleticism: 98,
            stamina: 88,
            basketballIQ: 84,
            decisionMaking: 82,
            impact: 85
        },
        advanced: {
            per: 26.2,
            ws: 7.8,
            bpm: 6.2,
            vorp: 2.2,
            trueShooting: 58.2,
            usage: 32.5
        },
        honors: ["2× All-Star", "1× All-NBA Team"]
    },
    {
        id: "lamelo",
        name: "LaMelo Ball",
        number: 1,
        team: "Charlotte Hornets",
        teamAbbr: "CHA",
        position: "PG",
        height: 201,
        weight: 82,
        age: 22,
        experience: 4,
        draft: { year: 2020, round: 1, pick: 3 },
        salary: "$36,016,200",
        ratings: {
            scoring: 85,
            efficiency: 78,
            ballHandling: 88,
            offBall: 78,
            clutch: 78,
            defense: 65,
            perimeter: 65,
            interior: 55,
            rebounding: 70,
            steals: 70,
            blocks: 48,
            playmaking: 88,
            turnover: 72,
            leadership: 75,
            durability: 75,
            athleticism: 86,
            stamina: 84,
            basketballIQ: 84,
            decisionMaking: 82,
            impact: 78
        },
        advanced: {
            per: 21.5,
            ws: 4.8,
            bpm: 3.2,
            vorp: 1.2,
            trueShooting: 54.5,
            usage: 29.5
        },
        honors: ["1× All-Star"]
    },
    {
        id: "trae",
        name: "Trae Young",
        number: 11,
        team: "Atlanta Hawks",
        teamAbbr: "ATL",
        position: "PG",
        height: 185,
        weight: 74,
        age: 25,
        experience: 6,
        draft: { year: 2018, round: 1, pick: 5 },
        salary: "$43,031,750",
        ratings: {
            scoring: 90,
            efficiency: 82,
            ballHandling: 92,
            offBall: 78,
            clutch: 88,
            defense: 58,
            perimeter: 58,
            interior: 48,
            rebounding: 48,
            steals: 65,
            blocks: 38,
            playmaking: 94,
            turnover: 72,
            leadership: 82,
            durability: 85,
            athleticism: 78,
            stamina: 90,
            basketballIQ: 90,
            decisionMaking: 88,
            impact: 84
        },
        advanced: {
            per: 24.2,
            ws: 7.2,
            bpm: 5.2,
            vorp: 2.2,
            trueShooting: 59.5,
            usage: 33.8
        },
        honors: ["2× All-Star", "1× All-NBA Team"]
    },
    {
        id: "siakam",
        name: "Pascal Siakam",
        number: 43,
        team: "Indiana Pacers",
        teamAbbr: "IND",
        position: "PF",
        height: 206,
        weight: 104,
        age: 30,
        experience: 8,
        draft: { year: 2016, round: 1, pick: 27 },
        salary: "$42,000,000",
        ratings: {
            scoring: 84,
            efficiency: 84,
            ballHandling: 82,
            offBall: 75,
            clutch: 78,
            defense: 80,
            perimeter: 72,
            interior: 86,
            rebounding: 78,
            steals: 68,
            blocks: 62,
            playmaking: 76,
            turnover: 80,
            leadership: 78,
            durability: 90,
            athleticism: 86,
            stamina: 88,
            basketballIQ: 84,
            decisionMaking: 80,
            impact: 80
        },
        advanced: {
            per: 22.5,
            ws: 8.8,
            bpm: 3.8,
            vorp: 2.0,
            trueShooting: 60.2,
            usage: 25.8
        },
        honors: ["1× NBA Champion", "2× All-Star", "1× Most Improved Player"]
    },
    {
        id: "抽",
        name: "Anthony Davis",
        number: 3,
        team: "Los Angeles Lakers",
        teamAbbr: "LAL",
        position: "PF",
        height: 208,
        weight: 106,
        age: 31,
        experience: 12,
        draft: { year: 2012, round: 1, pick: 1 },
        salary: "$43,219,333",
        ratings: {
            scoring: 88,
            efficiency: 86,
            ballHandling: 76,
            offBall: 78,
            clutch: 84,
            defense: 94,
            perimeter: 78,
            interior: 94,
            rebounding: 94,
            steals: 76,
            blocks: 94,
            playmaking: 70,
            turnover: 82,
            leadership: 80,
            durability: 78,
            athleticism: 88,
            stamina: 84,
            basketballIQ: 88,
            decisionMaking: 80,
            impact: 88
        },
        advanced: {
            per: 25.2,
            ws: 11.5,
            bpm: 6.2,
            vorp: 3.2,
            trueShooting: 58.8,
            usage: 26.8
        },
        honors: ["1× NBA Champion", "9× All-Star", "4× All-NBA Team", "3× All-Defensive Team"]
    }
];

const TEAMS = [
    { name: "Golden State Warriors", abbr: "GSW" },
    { name: "Denver Nuggets", abbr: "DEN" },
    { name: "Milwaukee Bucks", abbr: "MIL" },
    { name: "Los Angeles Lakers", abbr: "LAL" },
    { name: "Los Angeles Clippers", abbr: "LAC" },
    { name: "Phoenix Suns", abbr: "PHX" },
    { name: "Boston Celtics", abbr: "BOS" },
    { name: "Miami Heat", abbr: "MIA" },
    { name: "Dallas Mavericks", abbr: "DAL" },
    { name: "Minnesota Timberwolves", abbr: "MIN" },
    { name: "Philadelphia 76ers", abbr: "PHI" },
    { name: "Oklahoma City Thunder", abbr: "OKC" },
    { name: "New York Knicks", abbr: "NYK" },
    { name: "San Antonio Spurs", abbr: "SAS" },
    { name: "Cleveland Cavaliers", abbr: "CLE" },
    { name: "Sacramento Kings", abbr: "SAC" },
    { name: "Orlando Magic", abbr: "ORL" },
    { name: "New Orleans Pelicans", abbr: "NOP" },
    { name: "Memphis Grizzlies", abbr: "MEM" },
    { name: "Charlotte Hornets", abbr: "CHA" },
    { name: "Atlanta Hawks", abbr: "ATL" },
    { name: "Indiana Pacers", abbr: "IND" }
];

const POSITION_NAMES = {
    "PG": "控球后卫",
    "SG": "得分后卫",
    "SF": "小前锋",
    "PF": "大前锋",
    "C": "中锋"
};
